---
title: "Prop_Press_V.5.0"
author: "Josh Armstrong"
date: "2025-09-29"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Load in some libraries**

```{r, echo=FALSE, warning=FALSE, message=FALSE}

# Libraries used

library( tidyverse )
library( MASS )
library( ggpubr )          # Data visualization
library( cowplot )         # Data visualization
library( dotwhisker )      # Data visualization
library( moments )
library( rcompanion )
library( glmmTMB )         # Zero-inflated Gamma models
library( DHARMa )
library( SuppDists )
library( DescTools )
library( performance )
library( multcomp )
library( glmmTMB )
library( ggeffects )
library( jtools )
library( interactions )
library( knitr )
library( kableExtra )
library( ggbreak )
library( flextable )       # Creating tables
library( ggfx )
library( ggforce )
library( lme4 )
library( lmerTest )
library( smplot2 )
library( car )
library( marginaleffects )
library( betareg )
library( pscl )

std_mean <- function(x) sd(x)/sqrt(length(x))  # Function for calculating the standard error of data
```

# **Time to read in data and clean it up**

```{r, echo=FALSE}

pp_data <- read.csv( "Rockpool_Prop_Press.csv", stringsAsFactors = TRUE )  # Read in the data
pool_flood_data <- read.csv( "FiveYearAverages.csv", stringsAsFactors = TRUE )  # Read in some flood metrics of the pools

pp_data <- left_join( pp_data, pool_flood_data, by = "Pool_ID" ) # Appending pool flood data

pp_data$Pool_ID <- as.factor( pp_data$Pool_ID )  # Turn pool ID into factor
pp_data$Hyd_area_28 <- as.numeric( as.character( pp_data$Hyd_area_28 ) )  # Covert this column to numeric

pp_data <- pp_data %>% 
  rename( Hyd_area_0 = Hyd_Area_0 )  # Renaming this 1 column

sub_percov_data <- pp_data %>%
  dplyr::select( Pool_ID, c(20:25) )  # Subsetting the data to make converting to long easier

sub_pastcov_data <- pp_data %>%
  dplyr::select( Pool_ID, c(26:31) )  # Subsetting the data to make converting to long easier

add_cover_data <- pp_data %>%
  dplyr::select( Pool_ID, c(32:37) )  # Subsetting the data to make converting to long easier

sub_pool_data <- pp_data %>%
  dplyr::select( Pool_ID, Prop_Num:Can_Cov, Initial_drybio_g,Final_drybio_g, AvgDaysFlooded, AvgEvents ) # Pulling out pool level data

long_percov_data <- sub_percov_data %>% # Turning data to long format
  pivot_longer( cols = starts_with( "Per_Cover_"),
                names_to = "Day",
                names_prefix = "Per_Cover_",
                names_transform = as.integer,
                values_to = "Per_Cover" )

long_pastcov_data <- sub_pastcov_data %>% # Turning data to long format
  pivot_longer( cols = starts_with( "Past_Cover_"),
                names_to = "Day",
                names_prefix = "Past_Cover_",
                names_transform = as.integer,
                values_to = "Past_Cover" )

long_add_data <- add_cover_data %>% # Turning data to long format
  pivot_longer( cols = starts_with( "Add_Cover_"),
                names_to = "Day",
                names_prefix = "Add_Cover_",
                names_transform = as.integer,
                values_to = "Add_Cover" )

long_pastcov_data <- long_pastcov_data %>%  # Just selecting for 1 column
  dplyr::select( Past_Cover )

long_add_data <- long_add_data %>% # Just selecting for 1 column
  dplyr::select( Add_Cover )

long_pp_data <- cbind( long_percov_data, long_pastcov_data, long_add_data )  # Combining all of the columns of these three datasets


long_pp_data <- left_join( long_pp_data, sub_pool_data, by = "Pool_ID" ) # Appending pool data

long_pp_data <- long_pp_data %>% # Cleaning up a few things in the dataset
  mutate( Flood_ref = if_else( Day > 42, "Post-flood", "Pre-flood" ) ) %>%  # Creating a column for the variable of Pre- or Post-flood
  rename( Volume = Volume._cm3 ) %>%  # Renaming the volumn column
  filter( Day != 0)  # Removing the Day zero data because that is the beginning of the experiment

long_pp_data$Flood_ref <- as.factor( long_pp_data$Flood_ref ) # Changing this variable to a factor

long_pp_data <- long_pp_data %>%
  dplyr::mutate( Total_frags = Prop_Num*Prop_Size )  # Creating column that contains the total number of fragments added to the pool

# Create a model that predicts percent cover as a function of dry_biomass

glm.biomass <- glm( Per_Cover_84 ~ Final_drybio_g, pp_data, family = gaussian() )
summary( glm.biomass )

# Predict biomass for additions of fragments

## Create some data to help predict biomasses

Fragments <- c( 1, 4, 8, 12, 16, 24, 32, 48 )
Final_drybio_g <- c( 0.031, 0.123, 0.246, 0.372, 0.493, 0.744, 0.992, 1.488 )

Hyd_frag_sa <- data.frame( Fragments, Final_drybio_g ) # Combine vectors into a single dataframe

Hyd_frag_sa <- add_column( Hyd_frag_sa, fit = ( predict( glm.biomass, newdata = Hyd_frag_sa, type = "response" ) ) )  # Add column of predicted values

# Now lets add a few new columns

New_Long <- long_pp_data %>%
  filter( Prop_Num != 0 ) %>%  # Filter out the control pools
  mutate( Growth_Rate = ( log(Per_Cover + 1) - log(Past_Cover + Add_Cover + 1)) / 14,  # Create column for growth rate
          RGR = ( log(Per_Cover + 1) - log(Past_Cover + Add_Cover + 1)) / log(Past_Cover + Add_Cover + 1) / 14,  # Create column for RGR
          Flood_Hgt_m = Flood_Hgt_ft * 0.3048 )  # Convert feet to meters

# Subset data for the final time point

New_Long_Final <- New_Long %>%
  filter( Day == 84 )  # Only select last day's worth of data

# Now we need to change the 3 intro group to 2 before the flood

Post_flood <- New_Long %>%  # Make dataframe of post-flood data
  filter( Day > 56 )  # Only select data from after the flood 

Pre_flood <- New_Long %>%  # Make dataframe for pre-flood data
  filter( Day <= 56 ) %>%  # Only select data from before the flood
  dplyr::mutate( Prop_Num = if_else( Prop_Num == 3, 2, Prop_Num ))  # Change data Prop Num 3 treatment to 2 because the 3rd intro has not happened

Omni_Data <- rbind( Pre_flood, Post_flood )  # Combine the rows of both of these dataframes

#write.csv( Omni_Data_clean, "Omni_Data_clean.csv" )  # save a copy of this dataframe as a csv

```

# **Time to Model**

```{r}

# Overall % Coverage - zero-inflated (looks weird)

PerCov_zim1 <- glmmTMB( (Per_Cover + 1) ~ Prop_Num*Prop_Size + log(Volume) + Flood_ref + (1|Pool_ID),  # Create model
                      data = Omni_Data,  # Select data for the model
                      zi = ~., family = ziGamma( link = "log") )  # Clarify family of zero-infated models

summary( PerCov_zim1 )  # Look at model results
testDispersion( PerCov_zim1 )  # Test the dispersion of the model
r2( PerCov_zim1 )  # Check the R2 for the model
check_model( PerCov_zim1 )  # Check some other model stats
model_performance( PerCov_zim1 )  # Check the model performance

# Hurdle model (two-part)

# create a presence column
Omni_Data$presence <- as.integer(Omni_Data$Per_Cover > 0)  

# Part 1: logistic (presence vs absence)
PerCov_hur1 <- glmmTMB(presence ~ Prop_Num*Prop_Size + log(Volume) + Flood_ref + (1|Pool_ID),  # Create model
              data = Omni_Data,  # Select data for the model
              family = binomial)  # Set family for GLM as binomial distribution.

# Part 2: conditional model on positive values only (Gamma on positive amounts)
PerCov_hur2 <- glmmTMB(Per_Cover ~ Prop_Num*Prop_Size + log(Volume) + Flood_ref + (1|Pool_ID),  # Create model
              data = subset(Omni_Data, Per_Cover > 0),  # Select the subset of data to run the model with
              family = Gamma(link = "log"))  # Set family for GLM as log-linked Gamma distribution

summary(PerCov_hur1); summary(PerCov_hur2)  # Look at summaries of the models

# Growth Rate Model

PC_glm1 <- lmer( Growth_Rate ~ Prop_Num*Prop_Size + log(Volume) + Flood_ref + (1|Pool_ID), data = Omni_Data )  # Run a glm for growth rate

summary( PC_glm1 )  # Summary of model
plot(PC_glm1)  # Check model diagnostics
qqnorm(residuals(PC_glm1)); qqline(residuals(PC_glm1))  # Check residuals of model

# Relative Growth Rate Model

Omni_Data_clean <- subset(Omni_Data, !is.na(RGR) & !is.nan(RGR) & !is.infinite(RGR) )  # Subset data to remove NAN from data

PC_glm2 <- lmer( RGR ~ Prop_Num*Prop_Size + log(Volume) + Flood_ref + (1|Pool_ID), data = Omni_Data_clean ) # Run glm for RGR
summary( PC_glm2 )  # Summary of model

yj <- powerTransform(Omni_Data_clean$RGR, family = "yjPower")  # Perform a power transformation on RGR
yj$lambda   # best lambda value

Omni_Data_clean$RGR_trans <- yjPower(Omni_Data_clean$RGR, lambda = yj$lambda)  # Create a column for this transformed data

PC_glm3 <- lmer(RGR_trans ~ Prop_Num*Prop_Size + log(Volume) + Flood_ref + (1|Pool_ID),  # Run glm model with transformed RGR
     data = Omni_Data_clean)  # Select data for model

summary(PC_glm3) # Look at model summary

```

#**Correlation Between Biomass and Surface Area**

```{r}


New_long_no_outlier <- New_Long_Final %>%  # Removing the outlier data point for this correlation test.
  filter( Pool_ID != 331 ) 

ggplot( New_long_no_outlier, aes( Per_Cover, Final_drybio_g ) ) +  # Creating a correlation plot figure for the supplementals
  geom_point() +  # Make a scatter plot
  sm_statCorr() + # Add correlation test stats
  labs(x = "Percent Cover (%)",  # Label axes
       y = "Final dry biomass (g)" ) +
  theme( axis.line = element_line( colour = "black" ),  # Changing the theme of the figure
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_rect(fill = "white",colour = NA),
                 plot.background = element_rect(fill = "white",colour = NA) )

```


# **Time for some pretty figures**

```{r, echo=FALSE}

# Percent Coverage Figures

# --- 1. Build prediction grid ---

vol_mean <- mean(Omni_Data$Volume, na.rm = TRUE)

newdat <- expand.grid(
  Prop_Num  = sort(unique(Omni_Data$Prop_Num)),
  Prop_Size = sort(unique(Omni_Data$Prop_Size)),
  Flood_ref = sort(unique(Omni_Data$Flood_ref)),
  Volume    = vol_mean,
 # Pool_ID   = factor(NA, levels = levels(Omni_Data$Pool_ID)),
  stringsAsFactors = FALSE
)

# --- 2. Extract parameters and vcovs ---
coef_PerCov_hur1 <- fixef(PerCov_hur1)$cond
vcov_PerCov_hur1 <- vcov(PerCov_hur1)$cond
coef_PerCov_hur2 <- fixef(PerCov_hur2)$cond
vcov_PerCov_hur2 <- vcov(PerCov_hur2)$cond

# --- 3. Build design matrices ---
X_PerCov_hur1 <- model.matrix(formula(PerCov_hur1, fixed.only=TRUE)[-2], newdat)
X_PerCov_hur2 <- model.matrix(formula(PerCov_hur2, fixed.only=TRUE)[-2], newdat)

# --- 4. Bootstrap predictions ---
B <- 1000
set.seed(123)

boot_preds <- replicate(B, {
  # draw random parameter vectors
  b1 <- MASS::mvrnorm(1, coef_PerCov_hur1, vcov_PerCov_hur1)
  b2 <- MASS::mvrnorm(1, coef_PerCov_hur2, vcov_PerCov_hur2)

  # linear predictors
  eta1 <- X_PerCov_hur1 %*% b1
  eta2 <- X_PerCov_hur2 %*% b2

  # response scale transforms
  p_prob <- plogis(eta1)
  mu_pos <- exp(eta2)
  p_prob * mu_pos
}, simplify = FALSE)

boot_preds <- do.call(cbind, boot_preds)

# --- 5. Summarize predictions ---
newdat <- newdat %>%
  mutate(
    expected_cover     = rowMeans(boot_preds),
    expected_cover_sd  = apply(boot_preds, 1, sd),
    expected_cover_lo  = apply(boot_preds, 1, quantile, probs = 0.025),
    expected_cover_hi  = apply(boot_preds, 1, quantile, probs = 0.975)
  )

# --- 6. Rename for plotting ---
per_cover_new <- newdat %>%
  rename(
    Prop_Num = Prop_Num,
    Prop_Size = Prop_Size,
    Flood_ref = Flood_ref,
    Per_Cover = expected_cover,
    std.error = expected_cover_sd
  )

per_cover_new <- per_cover_new[-c(12, 15, 18), ] # Drop rows that actually don't exist

# Time to plot

Per_cover_2 <- ggplot( per_cover_new, aes( x = Prop_Size, y= Per_Cover, 
                                           group = as.factor( Prop_Num ),
                                           color = as.factor( Prop_Num ) )  )+
  geom_pointrange( aes( ymax = Per_Cover + std.error, ymin = Per_Cover - std.error ), 
                   position = position_dodge( width = 0.5 ), size = 0.5 ) +
  geom_line( position = position_dodge( width = 0.5 ), size = 1 ) +
  labs( x = "",
        y = "Percent Coverage (%)" ) +
  scale_color_manual(name = "Propagule Number\n(Number of Introduction Events)", 
                     values = c("#F4B154", "#25A353", "#09523D"))+
  facet_wrap( ~factor( Flood_ref, c("Pre-flood", "Post-flood" ) ), nrow = 1 ) +
  theme( axis.line = element_line( colour = "black" ),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_rect(fill = "white",colour = NA),
                 plot.background = element_rect(fill = "white",colour = NA),
         text=element_text( size=10, color = "black" ) )
Per_cover_2

# Growth Rate Figures

GR_Fig <- ggplot( Omni_Data, aes( x = Prop_Size, y= Growth_Rate, 
                                         fill = as.factor(Prop_Num), 
                                         color = as.factor(Prop_Num) )  )+
  #geom_jitter( size = 2, alpha = 0.3 ) +
  stat_smooth(method = "glm", se = TRUE,
       method.args = list(family = "gaussian"), linetype = "solid", alpha = 0.5 ) +
  labs( x = "",
        y = "AIR (delta % Cover/d)" ) +
  scale_color_manual(name = "Propagule Number\n(Number of Introduction Events)", 
                     values = c("#F4B154", "#25A353", "#09523D"))+
  scale_fill_manual( name = "Propagule Number\n(Number of Introduction Events)", 
                      values = c( "#F4B154", "#25A353", "#09523D") ) +
  facet_wrap( ~factor( Flood_ref, c("Pre-flood", "Post-flood" ) ),, scales = "free_x",
              nrow = 1 ) +
  geom_hline( yintercept = 0 ) +
  theme( axis.line = element_line( colour = "black" ),
         text=element_text( size=10, color = "black" ),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_rect(fill = "white",colour = NA),
                 plot.background = element_rect(fill = "white",colour = NA) )
GR_Fig

# Relative Growth Rate

RGR_Fig <- ggplot( Omni_Data_clean, aes( x = Prop_Size, y= RGR_trans, 
                                         fill = as.factor(Prop_Num), 
                                         color = as.factor(Prop_Num) )  )+
  #geom_jitter( size = 2, alpha = 0.3 ) +
  stat_smooth(method = "glm", se = TRUE,
       method.args = list(family = "gaussian"), linetype = "solid", alpha = 0.5 ) +
  labs( x = "Propagule Size\n(number of fragments added each introduction)",
        y = "RIR (%/d)" ) +
  scale_color_manual(name = "Propagule Number\n(Number of Introduction Events)", 
                     values = c("#F4B154", "#25A353", "#09523D"))+
  scale_fill_manual( name = "Propagule Number\n(Number of Introduction Events)", 
                      values = c( "#F4B154", "#25A353", "#09523D") ) +
  facet_wrap( ~factor( Flood_ref, c("Pre-flood", "Post-flood" ) ),, scales = "free_x",
              nrow = 1 ) +
  geom_hline( yintercept = 0 ) +
  theme( axis.line = element_line( colour = "black" ),
         text=element_text( size=10, color = "black" ),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_rect(fill = "white",colour = NA),
                 plot.background = element_rect(fill = "white",colour = NA) )
RGR_Fig

## Make a composite figure

ggarrange( Per_cover_2, GR_Fig, RGR_Fig, ncol = 1, nrow = 3,
           labels = c( "A","B","C"), align = "hv",  common.legend = T, legend = "bottom" )


```

# **Now to see the effect of that 3rd introduction**

```{r, echo=FALSE}

# Let's run two new analyses to explore the if that third intro had any effect on both SA, GR, &  RGR

# First add a new column to the dataset

New_Long_Final <- New_Long_Final %>%
  dplyr::mutate( Post_flood_intro = if_else( Prop_Num == 3, "Yes", "No" ) )  # Making a new categorical column of data

## Percent Cover first

### Note: Initially thought to do a t-test here but data is not normal so we will perform a Mann-Whitney test

Post_Flood_PerCover <- wilcox.test( Per_Cover ~ Post_flood_intro, data = New_Long_Final )  # Perform a Mann-Whitney test

Post_Flood_PerCover

Flood_PerCover <- New_Long_Final %>%  # Make a new dataframe with summarized data
  dplyr::group_by( Post_flood_intro ) %>%
  summarise( Mean_PC = mean( Per_Cover ),
             SE_PC = std_mean( Per_Cover ) )  

### Let's make a bar graph

PC_Flood_fig <- ggplot( Flood_PerCover, aes( Post_flood_intro, Mean_PC )) +
  geom_bar( stat = "identity", fill = "lightgreen", color = "black", size = 1.0 ) +
  geom_errorbar( aes( ymax = Mean_PC + SE_PC, ymin = Mean_PC - SE_PC ), width = 0.5, size = 1 ) +
  labs( y = "Mean percent\ncoverage (%)" ,
        x = "" ) +
  theme( axis.line = element_line( colour = "black" ),
         text=element_text( size=10, color = "black" ),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_rect(fill = "white",colour = NA),
                 plot.background = element_rect(fill = "white",colour = NA) ) 

PC_Flood_fig

## GR - another Mann-Whitney

New_Long_Final_clean <- subset(New_Long_Final, !is.na(RGR) & !is.nan(RGR) & !is.infinite(RGR) )  # Subsetting the data

Flood_GR <- wilcox.test( Growth_Rate ~ Post_flood_intro, data = New_Long_Final_clean )

Flood_GR

Flood_GR_sum <- New_Long_Final_clean %>%  # Making new dataframe with summarized data
  dplyr::group_by( Post_flood_intro ) %>%
  summarise( Mean_GR = mean( Growth_Rate ),
             SE_GR = std_mean( Growth_Rate ) )  

### Let's make a bar graph

GR_Flood_fig <- ggplot( Flood_GR_sum, aes( Post_flood_intro, Mean_GR )) +
  geom_bar( stat = "identity", fill = "salmon", color = "black", size = 1.0 ) +
  geom_errorbar( aes( ymax = Mean_GR + SE_GR, ymin = Mean_GR - SE_GR ), width = 0.5, size = 1 ) +
  labs( y = "Mean AIR\n(delta % cover/day)" ,
        x = "" ) +
  theme( axis.line = element_line( colour = "black" ),
         text=element_text( size=10, color = "black" ),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_rect(fill = "white",colour = NA),
                 plot.background = element_rect(fill = "white",colour = NA) ) 

GR_Flood_fig

## RGR - another Mann-Whitney

Omni_Clean_FIN <- Omni_Data_clean%>%
  filter( Day == 84 ) %>%
  dplyr::mutate( Post_flood_intro = if_else( Prop_Num == 3, "Yes", "No" ) )  # Subsetting the data

Flood_RGR <- wilcox.test( RGR_trans ~ Post_flood_intro, data = Omni_Clean_FIN )

Flood_RGR

Flood_RGR_sum <- Omni_Clean_FIN %>%  # Summarize the data in a new dataframe
  dplyr::group_by( Post_flood_intro ) %>%
  summarise( Mean_RGR = mean( RGR_trans ),
             SE_RGR = std_mean( RGR_trans ) )  

### Let's make a bar graph

RGR_Flood_fig <- ggplot( Flood_RGR_sum, aes( Post_flood_intro, Mean_RGR )) +
  geom_bar( stat = "identity", fill = "skyblue", color = "black", size = 1.0 ) +
  geom_errorbar( aes( ymax = Mean_RGR + SE_RGR, ymin = Mean_RGR - SE_RGR ), width = 0.5, size = 1 ) +
  geom_hline( yintercept = 0 ) +
  labs( y = "Mean RIR (%/d)" ,
        x = "Is there another introduction after flood?" ) +
  theme( axis.line = element_line( colour = "black" ),
         text=element_text( size=10, color = "black" ),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_rect(fill = "white",colour = NA),
                 plot.background = element_rect(fill = "white",colour = NA) ) 

RGR_Flood_fig

## Make a composite figure

ggarrange( PC_Flood_fig, GR_Flood_fig, RGR_Flood_fig, ncol = 1, nrow = 3,
           labels = c( "A","B", "C"), align = "hv",  common.legend = T)
```

# **Interaction Plot & Table for Interaction Plot**

```{r, echo=FALSE}

# Let's start with the plot

#mod_gamma  <- PerCov_zim1       # Zero-inflated Gamma model
mod_growth <- PC_glm1             # Gaussian GLM (Growth rate)
mod_rgr    <- PC_glm3                # Gaussian GLM (Power-transformed RGR)

# Get average marginal effects (AMEs)
#ame_gamma  <- avg_slopes(mod_gamma, type = "zi" )
ame_growth <- avg_slopes(mod_growth)
ame_rgr    <- avg_slopes(mod_rgr)

ame_growth$model <- "Invasion Rate"
ame_rgr$model <- "RIR"

effects_all <- bind_rows( ame_growth, ame_rgr )  # Combine all rows of the datasets

ggplot(effects_all, aes(x = estimate, y = term, color = model)) +  # Graph the data
  geom_point(position = position_dodge(width = 0.6), size = 2) +
  geom_errorbar(
    aes(xmin = conf.low, xmax = conf.high),
    position = position_dodge(width = 0.6),
    width = 0
  ) +
  facet_wrap(~ model, scales = "free_x") +
  theme_minimal(base_size = 13) +
  labs(
    x = "Average marginal effect (on response scale)",
    y = "Predictor"
  )

pd <- position_dodge(0.4)

coef_plot1 <- ggplot( effects_all, aes( x = factor( term ), estimate, color = model ) ) +  # Creating the coefficient plot
  geom_hline( yintercept = 0, color = gray( 1/2 ), lty = 2 ) +
  geom_point( position = pd, aes( color = model, shape = model ), size = 4 ) +
  geom_linerange(aes(x = term, 
                     ymin = conf.low,
                     ymax = conf.high ),
                     lwd = 1.2, position = pd ) +
  scale_color_manual( values =  c( "salmon", "skyblue" ),
                             labels = c( "Invasion Rate", "RIR" )) +
  scale_x_discrete( labels = c( "Volume" = "Volume",
                                "Prop_Size" = "Number of Fragments\nper Introduction",
                                "Prop_Num" = "Number of Introduction\nEvents",
                                "Flood_ref" = "Reference to Flood:\nPrior to Flood")) +
  coord_flip() +
  xlab( "Predictor" ) +
  ylab( "Average Marginal Effect") +
  theme( axis.line = element_line( colour = "black" ),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_rect(color = "black", fill=NA),
         text = element_text(colour="black"), 
                axis.title = element_text(size = 15), 
                axis.text = element_text(size = 15),
         legend.position = "bottom",
         legend.title = element_blank(),
         legend.text = element_text( size=20 ) )

coef_plot1

# Now time for the table

# Make a nice table with the summary table for stats

effects_all_g <- effects_all %>%
  as_grouped_data( groups = c("model"), columns = NULL)

ft_effects_all <- flextable( effects_all_g )  # Making a nice table

ft_effects_all <- set_header_labels( ft_effects_all,
   model = "",                                     
   term = "Predictor",
   estimate = "Estimate",
   std.error = "SE",
   statistic = "Statistic",
   p.value = "p-value",
   s.value = "s-value",
   conf.low = "Conf. Low",
   conf.high = "Conf. High" ) 

ft_effects_all <- align( ft_effects_all, i = 1, j = c( 2, 9 ), align = "center", part = "header" )  # Formatting the table to look nice
ft_effects_all <- align( ft_effects_all, i = NULL, j = c( 2, 9 ), align = "center", part = "body" )
ft_effects_all <- bold( ft_effects_all, i = NULL, j = 1, bold = TRUE, part = "body" )

ft_effects_all

print( ft_effects_all, preview = "pptx")  # Export table to powerpoint
```

# **Now Let's make some box plots for the distribution of data for the three measures**

```{r}

# First, box plot for percent coverage

Box_PC <- ggplot( Omni_Data, aes(as.factor(Prop_Size), Per_Cover,
                                 fill = as.factor(Prop_Num))) +
  geom_boxplot() +
  scale_fill_manual(name = "Propagule Number\n(Number of Introduction Events)", 
                     values = c("#F4B154", "#25A353", "#09523D"))+
  labs( x = "",
        y = "" ) +
  facet_wrap( ~factor( Flood_ref, c("Pre-flood", "Post-flood" ) ), nrow = 1 ) +
  theme( axis.line = element_line( colour = "black" ),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_rect(fill = "white",colour = NA),
                 plot.background = element_rect(fill = "white",colour = NA),
         text=element_text( size=10, color = "black" ) )


Box_PC

# Box plot for growth rate

Box_GR <- ggplot( Omni_Data, aes(as.factor(Prop_Size), Growth_Rate,
                                 fill = as.factor(Prop_Num))) +
  geom_boxplot() +
  scale_fill_manual(name = "Propagule Number\n(Number of Introduction Events)", 
                     values = c("#F4B154", "#25A353", "#09523D"))+
  labs( x = "",
        y = "" ) +
  facet_wrap( ~factor( Flood_ref, c("Pre-flood", "Post-flood" ) ), nrow = 1 ) +
  geom_hline( yintercept = 0 ) +
  theme( axis.line = element_line( colour = "black" ),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_rect(fill = "white",colour = NA),
                 plot.background = element_rect(fill = "white",colour = NA),
         text=element_text( size=10, color = "black" ) )

Box_GR

# Box plot for RGR

Box_RGR <- ggplot( Omni_Data_clean, aes(as.factor(Prop_Size), RGR_trans,
                                 fill = as.factor(Prop_Num))) +
  geom_boxplot() +
  scale_fill_manual(name = "Propagule Number\n(Number of Introduction Events)", 
                     values = c("#F4B154", "#25A353", "#09523D"))+
  labs( x = "Propagule Size\n(number of fragments added each introduction)",
        y = "") +
  facet_wrap( ~factor( Flood_ref, c("Pre-flood", "Post-flood" ) ), nrow = 1 ) +
  geom_hline( yintercept = 0 ) +
  theme( axis.line = element_line( colour = "black" ),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_rect(fill = "white",colour = NA),
                 plot.background = element_rect(fill = "white",colour = NA),
         text=element_text( size=10, color = "black" ) )

Box_RGR

# Lets pu all 6 figures together

ggarrange( Per_cover_2, Box_PC,
           GR_Fig, Box_GR,
           RGR_Fig, Box_RGR,
           ncol = 2, nrow = 3,
           labels = c( "A","B","C","D","E","F"), align = "v",  
           common.legend = T, legend = "bottom" )
```

# **Figuring out some means**

```{r}

# Mean growth rates - Summarized data

GR_means <- Omni_Data %>%
  dplyr::group_by( Flood_ref ) %>%
  dplyr::summarise( Mean_GR = mean( Growth_Rate, na.rm = TRUE ),
                    SD_GR = sd( Growth_Rate, na.rm = TRUE ), )

# Mean relative growth rates - Summarized data

RGR_means <- Omni_Data_clean %>%
  dplyr::group_by( Flood_ref ) %>%
  dplyr::summarise( Mean_RGR = mean( RGR_trans, na.rm = TRUE ),
                    SD_RGR = sd( RGR_trans, na.rm = TRUE ) )

Omni_Data_clean <- Omni_Data_clean %>%
  dplyr::mutate( Pos_RGR = if_else( RGR_trans > 0, "Yes", "No" ) )

Omni_Data_clean$Pos_RGR <- as.factor(Omni_Data_clean$Pos_RGR)

RGR_pos <- Omni_Data_clean %>%
  dplyr::group_by( Flood_ref, Pos_RGR ) %>%
  summarise( Number = n())

# Mean Percent coverage 1 intro compared to 2 intros - Summarized data

Intro_cover_means <- Omni_Data_clean %>%
  filter( Day == 42 ) %>%
  dplyr::group_by( Prop_Num ) %>%
  dplyr::summarise( Mean_Cover = mean( Per_Cover, na.rm = TRUE),
                    SD_Cover = sd( Per_Cover, na.rm = TRUE ) )
  
Intro_cover_means_post <- Omni_Data_clean %>%
  filter( Day == 56 ) %>%
  dplyr::group_by( Prop_Num ) %>%
  dplyr::summarise( Mean_Cover = mean( Per_Cover, na.rm = TRUE),
                    SD_Cover = sd( Per_Cover, na.rm = TRUE ) )

# Mean Percent coverage 4 frags compared to 16 frags - Summarized data

Frag_cover_means <- Omni_Data_clean %>%
  filter( Day == 42 ) %>%
  dplyr::group_by( Prop_Size ) %>%
  dplyr::summarise( Mean_Cover = mean( Per_Cover, na.rm = TRUE),
                    SD_Cover = sd( Per_Cover, na.rm = TRUE ) )
  
Frag_cover_means_post <- Omni_Data_clean %>%
  filter( Day == 56 ) %>%
  dplyr::group_by( Prop_Size ) %>%
  dplyr::summarise( Mean_Cover = mean( Per_Cover, na.rm = TRUE),
                    SD_Cover = sd( Per_Cover, na.rm = TRUE ) )

# Variation in percent coverage pre and post flood - Summarized data

Per_cover_var <- Omni_Data_clean %>%
  filter( Day <= 42 ) %>%
  dplyr::summarise( Mean_Cover = mean( Per_Cover, na.rm = TRUE),
                    SD_Cover = sd( Per_Cover, na.rm = TRUE ) )

Per_cover_var_aft <- Omni_Data_clean %>%
  filter( Day > 42 ) %>%
  dplyr::summarise( Mean_Cover = mean( Per_Cover, na.rm = TRUE),
                    SD_Cover = sd( Per_Cover, na.rm = TRUE ) )
 

```


